# Copyright 2022 InstaDeep Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import logging
import subprocess
import textwrap
import time
from typing import Tuple

system_num_to_name = {
    1: ["ff_ippo_tabular_split"],
    2: ["ff_ppo_central_tabular"],
    3: ["ff_ppo_central_factored_tabular"],
    4: ["ff_ppo_central_factored"],
    5: ["ff_ippo"],
    6: ["ff_mappo"],
    7: ["ff_sable"],
    8: ["ff_ppo_central"],
    9: ["ff_ppo_central_autoreg_tabular"],
    10: ["ff_ppo_central_autoreg_chained_tabular"],
}

env_seed_to_system_seeds = {
    42: ["0", "1"],
    43: ["2", "3"],
    44: ["4", "5"],
    45: ["6", "7"],
    46: ["8", "9"],
}

num_agents = [2, 3, 4, 5, 6, 7]
num_actions = [2, 3, 4, 5, 6, 7, 8]
env_seeds = [42, 43, 44, 45, 46]
num_steps = [
    "200M",
    # "test",
]
is_shadowed_list = [False]


def get_eval_updates(step_count: str) -> Tuple[int, int]:
    if step_count == "200M":
        return (24400, 2440)
    elif step_count == "test":
        return (20, 5)
    else:
        raise ValueError(f"Invalid step count: {step_count}")


def get_script_contents(
    system_name: str,
    system_seed: str,
    env_seed: int,
    task_name: str,
    num_agent: int,
    num_actions: int,
    num_steps: str,
    is_shadowed: bool = False,
) -> str:
    timestamp = time.strftime("%Y%m%d-%H%M%S")

    if system_name == "ff_ppo_central":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central.py"
    elif system_name == "ff_mappo":
        system_run_file = "mava/systems/ppo/anakin/ff_mappo.py"
    elif system_name == "ff_ippo_tabular_split":
        system_run_file = "mava/systems/ppo/anakin/ff_ippo_tabular_split.py"
    elif system_name == "ff_sable":
        system_run_file = "mava/systems/sable/anakin/ff_sable.py"
    elif system_name == "ff_ippo":
        system_run_file = "mava/systems/ppo/anakin/ff_ippo.py"
    elif system_name == "ff_ppo_central_tabular":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_tabular.py"
    elif system_name == "ff_ppo_central_factored_tabular":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_factored_tabular.py"
    elif system_name == "ff_ppo_central_factored":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_factored.py"
    elif system_name == "ff_ppo_central_autoreg_tabular":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_autoreg_tabular.py"
    elif system_name == "ff_ppo_central_autoreg_chained_tabular":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_autoreg_chained_tabular.py"

    neptune_tag = '["explore-same-param-rerun"]'
    # neptune_tag = '["shadowed-same-param-rerun"]'
    # neptune_tag = '["test-tpu-rerun"]'
    num_updates, num_evals = get_eval_updates(num_steps)

    shadowed_str = "True" if is_shadowed else "False"

    script = f"""\
        #!/bin/bash
        # Script auto-generated by experiment_launch_exps.py on {timestamp}
        python {system_run_file} -m system.seed={system_seed} \\
        env=generalised-matrax \\
        arch.num_evaluation={num_evals} system.num_updates={num_updates} \\
        env.scenario.task_name={task_name} env.scenario.task_config.num_agents={num_agent} \\
        env.scenario.task_config.num_actions={num_actions} \\
        env.scenario.task_config.key_integer={env_seed} \\
        logger.kwargs.neptune_tag='{neptune_tag}' \\
        env.kwargs.generate_shadowed_payoffs={shadowed_str} \\
        """

    return textwrap.dedent(script)


def should_run(system_name: str, task_name: str) -> bool:
    return True


def make_task_name(num_agents: int, num_actions: int) -> str:
    return f"matrax-{num_agents}-ag-{num_actions}-act"


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    parser = argparse.ArgumentParser(description="Launch 200M experiments for a selected system.")
    parser.add_argument(
        "-s",
        "--system_name",
        type=int,
        default=1,
        choices=list(system_num_to_name.keys()),
        help=(
            "Numeric system selector. "
            "Maps to entries in system_num_to_name (e.g. 1 -> ff_ippo_tabular_split)."
        ),
    )
    args = parser.parse_args()

    system_names = system_num_to_name[args.system_name]

    for is_shadowed in is_shadowed_list:
        for num_step in num_steps:
            for system_name in system_names:
                for num_agent in num_agents:
                    for num_action in num_actions:
                        for env_seed in env_seed_to_system_seeds:
                            for system_seed in env_seed_to_system_seeds[env_seed]:
                                task_name = make_task_name(num_agent, num_action)

                                if should_run(system_name, task_name):
                                    logging.info(f"Running experiment {system_name} - {task_name}")

                                    script_contents = get_script_contents(
                                        system_name=system_name,
                                        env_seed=int(env_seed),
                                        system_seed=system_seed,
                                        task_name=task_name,
                                        num_agent=num_agent,
                                        is_shadowed=is_shadowed,
                                        num_actions=num_action,
                                        num_steps=num_step,
                                    )
                                    with open("run.sh", "w") as f:
                                        f.write(script_contents)
                                    try:
                                        subprocess.run(["./run.sh"], check=True)
                                        logging.info("Experiment launched successfully")
                                        time.sleep(5)

                                    except subprocess.CalledProcessError as e:
                                        logging.error(f"Error launching the experiment: {e}")
