# Copyright 2022 InstaDeep Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import subprocess
import textwrap
import time


def get_script_contents(
    system_name: str,
    system_seed: int,
) -> str:
    timestamp = time.strftime("%Y%m%d-%H%M%S")

    if system_name == "ff_ppo_central":
        system_run_file = "mava/systems/ppo/ff_ppo_central.py"
    elif system_name == "ff_ippo":
        system_run_file = "mava/systems/ppo/ff_ippo.py"
    elif system_name == "ff_mappo":
        system_run_file = "mava/systems/ppo/ff_mappo.py"
    elif system_name == "ff_ippo_tabular":
        system_run_file = "mava/systems/ppo/ff_ippo_tabular.py"
    elif system_name == "ff_ppo_central_tabular":
        system_run_file = "mava/systems/ppo/ff_ppo_central_tabular.py"
    elif system_name == "ff_ippo_tabular_split":
        system_run_file = "mava/systems/ppo/ff_ippo_tabular_split.py"
    elif system_name == "mat":
        system_run_file = "mava/systems/mat/anakin/mat.py"
    elif system_name == "ff_sable":
        system_run_file = "mava/systems/sable/anakin/ff_sable.py"
    elif system_name == "ff_ppo_central_factored":
        system_run_file = "mava/systems/ppo/anakin/ff_ppo_central_factored.py"

    system_run_seed = int(system_seed)

    script = f"""\
        #!/bin/bash
        # Script auto-generated by experiment_launch_exps.py on {timestamp}
        python {system_run_file} -m system.seed={system_run_seed} \\
        """

    return textwrap.dedent(script)


system_seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
system_names = [
    # "ff_ippo_tabular",
    # "ff_ippo_tabular_split",
    # "ff_ppo_central_tabular",
    # "ff_ippo",
    # "ff_mappo",
    # "ff_ppo_central",
    "ff_ppo_central_factored",
    "ff_sable",
    "mat",
]


def should_run(system_name: str, task_name: str) -> bool:
    return True


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    for system_name in system_names:
        for system_seed in system_seeds:
            task_name = "Climbing"
            if should_run(system_name, task_name):
                logging.info(f"Running experiment {system_name} - {task_name}")

                script_contents = get_script_contents(
                    system_name=system_name,
                    system_seed=system_seed,
                )
                with open("run.sh", "w") as f:
                    f.write(script_contents)
                try:
                    subprocess.run(["./run.sh"], check=True)
                    logging.info("Experiment launched successfully")

                except subprocess.CalledProcessError as e:
                    logging.error(f"Error launching the experiment: {e}")
