#!/bin/bash
# Script auto-generated by experiment_launch_exps.py on 20241204-213342
python mava/systems_tuning/ppo/anakin/ff_ippo.py -m env=generalised-matrax \
arch.num_envs=32 \
logger.kwargs.neptune_tag='["first-carbs-sweep"]' \
logger.use_neptune=False \
logger.use_json=False \
