#!/bin/bash
# Script auto-generated by experiment_launch_exps.py on 20241015-223722
python mava/systems/ppo/ff_ippo.py -m system.seed=0 \
arch.num_evaluation=3 system.num_updates=6 \
env=lbf env/scenario=15x15-3p-5f
