#!/bin/bash
# Script auto-generated by experiment_launch_exps.py on 20241201-090630
python mava/systems/ppo/anakin/ff_ppo_central_tabular.py -m system.seed=0 \
env=generalised-matrax \
arch.num_envs=24 \
arch.num_evaluation=4 system.num_updates=8 \
env.scenario.task_name=matrax-4-ag-4-act env.scenario.task_config.num_agents=4 \
env.scenario.task_config.num_actions=4 \
env.scenario.task_config.key_integer=42 \
logger.kwargs.neptune_tag='["multi-system-exp-test","delete"]' \
env.kwargs.generate_shadowed_payoffs=True \
logger.use_neptune=True \
logger.use_json=True \
