# The config of the 15x15-3p-5f scenario with the VectorObserver set as default
task_name: 30x30-7p-7f

task_config:
  grid_size: 30
  fov: 30
  num_agents: 7
  num_food: 7
  max_agent_level: 2
  force_coop: False
