actor_network:
  pre_torso:
    network_type: cnn
    network_kwargs:
      conv_n_channels: 32
      activation: relu
  post_torso: ~

critic_network:
  pre_torso:
    network_type: cnn
    network_kwargs:
      conv_n_channels: 32
      activation: relu
  post_torso: ~
