actor_network:
  pre_torso:
    network_type: mlp
    network_kwargs:
      layer_sizes: [128, 128]
      use_layer_norm: False
      activation: relu
  post_torso:
    network_type: mlp
    network_kwargs:
      layer_sizes: [128, 128]
      use_layer_norm: False
      activation: relu

critic_network:
  pre_torso:
    network_type: mlp
    network_kwargs:
      layer_sizes: [128, 128]
      use_layer_norm: False
      activation: relu
  post_torso:
    network_type: mlp
    network_kwargs:
      layer_sizes: [128, 128]
      use_layer_norm: False
      activation: relu
