actor_network:
  pre_torso:
    _target_: mava.networks.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
  post_torso:
    _target_: mava.networks.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
    post_torso: True

critic_network:
  pre_torso:
    _target_: mava.networks.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
  post_torso:
    _target_: mava.networks.MLPTorso
    layer_sizes: [128, 128]
    use_layer_norm: False
    post_torso: True
