defaults:
  - logger: ff_ppo_central
  - arch: anakin
  - system: ppo/ff_ppo_central
  - network: mlp  # [mlp, continuous_mlp, cnn]
  - env: matrax  # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_
