defaults:
  - logger: logger
  - arch: anakin
  - system: ppo/rec_ppo_central
  - network: rnn  # [mlp, continuous_mlp, cnn]
  - env: rware # [cleaner, connector, gigastep, lbf, mabrax, matrax, rware, smax]
  - _self_

hydra:
  searchpath:
    - file://mava/configs
