# Copyright 2022 InstaDeep Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import argparse
import logging
import subprocess
import textwrap
import time

tpu_idx_to_run_file = {
    1: "mava/systems_tuning/ppo/anakin/rec_ippo.py",
    2: "mava/systems_tuning/ppo/anakin/rec_mappo.py",
    3: "mava/systems_tuning/mat/anakin/mat.py",
    4: "mava/systems_tuning/sable/anakin/ff_sable.py",
    5: "mava/systems_tuning/sable/anakin/rec_sable.py",
    6: "mava/systems_tuning/ppo/anakin/rec_ppo_central.py",
    7: "mava/systems_tuning/ppo/anakin/ff_ippo_tabular_split.py",
    8: "mava/systems_tuning/ppo/anakin/ff_ppo_central_tabular.py",
    9: "mava/systems_tuning/ppo/anakin/rec_ppo_central_factored.py",
}


def get_script_contents(
    tpu_idx: int,
) -> str:
    timestamp = time.strftime("%Y%m%d-%H%M%S")

    system_run_file = tpu_idx_to_run_file[tpu_idx]

    neptune_tag = '["first-carbs-sweep-repeated-matrax"]'

    # TODO: use_netpune shoudl be True
    script = f"""\
        #!/bin/bash
        # Script auto-generated by experiment_launch_exps.py on {timestamp}[]
        python {system_run_file} -m env=generalised-matrax \\
        arch.num_envs=8 \\
        logger.kwargs.neptune_tag='{neptune_tag}' \\
        logger.use_neptune=True \\
        logger.use_json=False \\
        """

    return textwrap.dedent(script)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--tpu-idx", type=int, required=True, default=1)
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO)

    script_contents = get_script_contents(tpu_idx=args.tpu_idx)
    with open("run.sh", "w") as f:
        f.write(script_contents)
    try:
        subprocess.run(["./run.sh"], check=True)
        logging.info("Experiment launched successfully")
        time.sleep(5)

    except subprocess.CalledProcessError as e:
        logging.error(f"Error launching the experiment: {e}")
