# Copyright 2022 InstaDeep Ltd. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import logging
import subprocess
import textwrap
import time
from typing import Tuple

system_name_to_run_file = {
    "ff_ippo": "mava/systems/ppo/anakin/ff_ippo.py",
    "ff_mappo": "mava/systems/ppo/anakin/ff_mappo.py",
    "rec_ippo": "mava/systems/ppo/anakin/rec_ippo.py",
    "rec_mappo": "mava/systems/ppo/anakin/rec_mappo.py",
    "mat": "mava/systems/mat/anakin/mat.py",
    "ff_sable": "mava/systems/sable/anakin/ff_sable.py",
    "rec_sable": "mava/systems/sable/anakin/rec_sable.py",
    "ff_ppo_central": "mava/systems/ppo/anakin/ff_ppo_central.py",
    "ff_ippo_tabular_split": "mava/systems/ppo/anakin/ff_ippo_tabular_split.py",
    "ff_ippo_tabular": "mava/systems/ppo/anakin/ff_ippo_tabular.py",
    "ff_ppo_central_tabular": "mava/systems/ppo/anakin/ff_ppo_central_tabular.py",
}

system_names = [
    "ff_ippo",
    "ff_mappo",
    "rec_ippo",
    "rec_mappo",
    "mat",
    "ff_sable",
    "rec_sable",
    "ff_ppo_central",
    "ff_ippo_tabular_split",
    "ff_ippo_tabular",
    "ff_ppo_central_tabular",
]

system_seeds = ["0", "1", "2"]

# num_agents = [2, 3, 4, 5, 6, 7]
# num_actions = [2, 3, 4, 5, 6, 7, 8, 9, 10]
num_agents = [3, 4]
num_actions = [3, 4]
env_seeds = [42]
num_steps = [
    # "test",
    # "1M",
    # "5M",
    "10M",
    # "20M",
    # "50M",
    # "500M",
]
is_shadowed_list = [True]


def get_eval_updates(step_count: str) -> Tuple[int, int]:
    if step_count == "test":
        return (8, 4)
    elif step_count == "1M":
        return (165, 33)
    elif step_count == "5M":
        return (815, 163)
    elif step_count == "10M":
        return (1630, 326)
    elif step_count == "20M":
        return (3255, 651)
    elif step_count == "50M":
        return (8140, 814)
    elif step_count == "500M":
        return (81400, 814)


def should_run(system_name: str, scenario_name: str) -> bool:
    return True


def make_task_name(num_agents: int, num_actions: int) -> str:
    return f"matrax-{num_agents}-ag-{num_actions}-act"


def get_script_contents(
    system_name: str,
    system_seed: str,
    env_seed: int,
    task_name: str,
    num_agent: int,
    num_actions: int,
    num_steps: str,
    is_shadowed: bool = False,
) -> str:
    timestamp = time.strftime("%Y%m%d-%H%M%S")

    system_run_file = system_name_to_run_file[system_name]

    neptune_tag = f'["multi-system-exp-{num_steps}","delete"]'
    num_updates, num_evals = get_eval_updates(num_steps)

    shadowed_str = "True" if is_shadowed else "False"

    script = f"""\
        #!/bin/bash
        # Script auto-generated by experiment_launch_exps.py on {timestamp}
        python {system_run_file} -m system.seed={system_seed} \\
        env=generalised-matrax \\
        arch.num_envs=24 \\
        arch.num_evaluation={num_evals} system.num_updates={num_updates} \\
        env.scenario.task_name={task_name} env.scenario.task_config.num_agents={num_agent} \\
        env.scenario.task_config.num_actions={num_actions} \\
        env.scenario.task_config.key_integer={env_seed} \\
        logger.kwargs.neptune_tag='{neptune_tag}' \\
        env.kwargs.generate_shadowed_payoffs={shadowed_str} \\
        logger.use_neptune=True \\
        logger.use_json=True \\
        """

    return textwrap.dedent(script)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)

    for is_shadowed in is_shadowed_list:
        for num_step in num_steps:
            for system_seed in system_seeds:
                for num_agent in num_agents:
                    for num_action in num_actions:
                        for env_seed in env_seeds:
                            for system_name in system_names:
                                task_name = make_task_name(num_agent, num_action)

                                if should_run(system_name, task_name):
                                    logging.info(f"Running experiment {system_name} - {task_name}")

                                    script_contents = get_script_contents(
                                        system_name=system_name,
                                        env_seed=env_seed,
                                        system_seed=system_seed,
                                        task_name=task_name,
                                        num_agent=num_agent,
                                        is_shadowed=is_shadowed,
                                        num_actions=num_action,
                                        num_steps=num_step,
                                    )
                                    with open("run.sh", "w") as f:
                                        f.write(script_contents)
                                    try:
                                        subprocess.run(["./run.sh"], check=True)
                                        logging.info("Experiment launched successfully")
                                        time.sleep(5)

                                    except subprocess.CalledProcessError as e:
                                        logging.error(f"Error launching the experiment: {e}")
