# ---Environment Configs---
defaults:
  - _self_

env_name: GeneralMatrax  # Used for logging purposes.

scenario:
  name: GeneralMatrax
  task_name: matrax-3-ag-4-act

  task_config:
    key_integer: 41
    num_agents: 3
    num_actions: 4

# Defines the metric that will be used to evaluate the performance of the agent.
# This metric is returned at the end of an experiment and can be used for hyperparameter tuning.
eval_metric: episode_return

# Whether the environment observations encode implicit agent IDs. If True, the AgentID wrapper is not used.
# This should not be changed.
implicit_agent_id: False
# Whether or not to log the winrate of this environment. This should not be changed as not all
# environments have a winrate metric.
log_win_rate: False

kwargs:
  keep_state: False
  time_limit: 1
  generate_shadowed_payoffs: True
